#  Copyright (C) 2026 LEIDOS.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

import argparse
import yaml
import subprocess
import shutil
import time
from pathlib import Path
from scenario_generator import ScenarioGenerator
from data_collector import DataCollector
from data_analyzer import DataAnalyzer
from runtime_preparation import prepare_host_directories
from scenario_resources import ScenarioResourceManager
from scenario_topology import apply_scenario_topology


# Shell convention: an exit caused by signal N uses status 128 + N. SIGINT,
# generated by Ctrl+C, is signal 2, so Scenario Runner exits with status 130.
SIGINT_EXIT_CODE = 130


class ScenarioRunner:
    """Run or generate test cases defined in a scenario configuration."""

    def __init__(
        self,
        config_path: str = "config/scenarios/town10.yaml",
        generate_only: bool = False,
        test_case_label: str = None,
    ):
        self.config_path = Path(config_path)
        self.generate_only = generate_only
        self.test_case_label = test_case_label
        self.test_cases = []
        self.tmp_dir = Path("tmp").resolve()
        self.resource_manager = ScenarioResourceManager(self.tmp_dir)
        self.collector = DataCollector()
        self.analyzer = DataAnalyzer()

    def load_parameters(self):
        if not self.config_path.exists():
            raise FileNotFoundError(f"{self.config_path} not found")
        with open(self.config_path, 'r') as f:
            data = yaml.safe_load(f)
        self.test_cases = data.get("test_cases", [])
        if not self.test_cases:
            raise ValueError(f"No 'test_cases' found in {self.config_path}")
        print(f"Loaded {len(self.test_cases)} scenario(s)")

    def _selected_test_cases(self):
        """Return indexed test cases, optionally filtered by label."""

        indexed_cases = list(enumerate(self.test_cases, start=1))
        if self.test_case_label is None:
            return indexed_cases

        matches = [
            (index, case)
            for index, case in indexed_cases
            if case.get("label", f"scenario_{index}") == self.test_case_label
        ]
        if not matches:
            available = ", ".join(
                case.get("label", f"scenario_{index}")
                for index, case in indexed_cases
            )
            raise ValueError(
                f"Test case {self.test_case_label!r} was not found. "
                f"Available test cases: {available}"
            )
        if len(matches) > 1:
            raise ValueError(
                f"Test case label {self.test_case_label!r} is not unique"
            )
        return matches

    def _generate_case(self, idx: int, case: dict) -> tuple[dict, str, dict]:
        """Normalize one case and generate its runtime files."""

        label = case.get("label", f"scenario_{idx}")
        scenario_resources = self.resource_manager.resolve(case, label)
        case = apply_scenario_topology(case)
        print(f"\n=== Scenario {idx}: {label} ===")

        if self.tmp_dir.exists():
            shutil.rmtree(self.tmp_dir)
        self.tmp_dir.mkdir()

        param_path = self.tmp_dir / f"{label}_scenario.yaml"
        with param_path.open("w", encoding="utf-8") as scenario_file:
            yaml.dump(
                {
                    "env_settings": case["env_settings"],
                    "scenario_resources": scenario_resources,
                },
                scenario_file,
                default_flow_style=False,
            )
        print(f"Generated {param_path}")
        generator = ScenarioGenerator(
            config_path=str(param_path),
            compose_root=self.config_path.parent,
        )
        return case, label, generator.generate()

    def _execute_case(
        self, idx: int, case: dict, label: str, scripts: dict
    ) -> tuple[Path, dict]:
        """Execute generated scripts and collect one case's outputs."""

        start_sh = scripts["start_script"]
        stop_sh = scripts["stop_script"]
        print("Preparing host directories...")
        protected_directories = prepare_host_directories(case)

        print("Clearing source log directories...")
        self.collector.clear_sources(case, protected_directories)

        try:
            print(f"Launching: {start_sh}")
            subprocess.run(["bash", start_sh], check=True)
            runtime = case.get("runtime_seconds", 60)
            print(f"Running {label} for  {runtime} seconds...")
            time.sleep(runtime)
        except subprocess.CalledProcessError as e:
            print(f"Start script {start_sh} failed with error : {e}")
        except KeyboardInterrupt:
            print("Interrupt received; stopping the scenario...")
            raise
        finally:
            print(f"Stopping: {stop_sh}")
            stop_result = subprocess.run(["bash", stop_sh], check=False)
            if stop_result.returncode != 0:
                print(
                    f"Warning: stop script exited with "
                    f"{stop_result.returncode}"
                )
            print("Restoring host directory permissions...")
            prepare_host_directories(case)

        print("Collecting data outputs...")
        case_dir = self.collector.collect(idx, case)
        print("Clearing collected source logs...")
        self.collector.clear_sources(case, protected_directories)
        shutil.rmtree(self.tmp_dir)
        print(f"Cleaned {self.tmp_dir}")
        print(f"Scenario {idx} complete.\n")
        return case_dir, case

    def _run_one(self, idx: int, case: dict) -> tuple[Path, dict] | None:
        case, label, scripts = self._generate_case(idx, case)
        if self.generate_only:
            print(f"Scenario {idx} generated. Inspect files in {self.tmp_dir}.\n")
            return None
        return self._execute_case(idx, case, label, scripts)

    def run(self):
        if not self.test_cases:
            self.load_parameters()

        selected_cases = self._selected_test_cases()
        if self.test_case_label is not None:
            print(f"Selected test case: {self.test_case_label}")

        collected = []
        for i, case in selected_cases:
            try:
                result = self._run_one(i, case)
                if result:
                    collected.append(result)
            except KeyboardInterrupt:
                print(f"Scenario {i} interrupted by user")
                if not self.generate_only and self.tmp_dir.exists():
                    shutil.rmtree(self.tmp_dir)
                raise SystemExit(SIGINT_EXIT_CODE)
            except Exception as e:
                print(f"Scenario {i} failed: {e}")
                if not self.generate_only and self.tmp_dir.exists():
                    shutil.rmtree(self.tmp_dir)

        analysis_failures = {}
        for case_dir, case in collected:
            print("Running data analysis...")
            label = case.get("label", str(case_dir))
            failures = self.analyzer.analyze(case_dir, case)
            if failures:
                analysis_failures[label] = failures

        if analysis_failures:
            print("\n=== Data analysis failures ===")
            for label, failures in analysis_failures.items():
                print(f"{label}:")
                for failure in failures:
                    print(f"  - {failure}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Run CDASim scenarios")
    parser.add_argument(
        "--config",
        default="config/scenarios/town10.yaml",
        metavar="PATH",
        help=(
            "Scenario configuration file "
            "(default: config/scenarios/town10.yaml)"
        ),
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Generate environment and start/stop files without executing them",
    )
    parser.add_argument(
        "--test-case",
        metavar="LABEL",
        help="Run or generate only the test case with this label",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = parse_args()
    ScenarioRunner(
        config_path=args.config,
        generate_only=args.generate_only,
        test_case_label=args.test_case,
    ).run()
