#  Copyright (C) 2026 LEIDOS.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

import argparse
import math
import stat
import yaml
import subprocess
import shutil
import time
from pathlib import Path
from scenario_generator import ScenarioGenerator
from data_collector import DataCollector
from data_analyzer import DataAnalyzer
from scenario_topology import apply_scenario_topology


CONFIG_DIRECTORY = Path(__file__).resolve().parent / "config"
INFRASTRUCTURE_CONFIG_DIRECTORY =  CONFIG_DIRECTORY / "infrastructure"
MAP_DIRECTORY = CONFIG_DIRECTORY / "maps"
ROUTE_DIRECTORY = CONFIG_DIRECTORY / "routes"
CDASIM_CONFIG_DIRECTORY =  CONFIG_DIRECTORY / "cdasim"
MAP_TARGET_DIRECTORY = Path("/opt/carma/maps")
ROUTE_TARGET_DIRECTORY = Path("/opt/carma/routes")
SIMULATION_TMP_DIRECTORY = Path("/opt/carma-simulation/tmp")
SIMULATION_LOG_DIRECTORY = Path("/opt/carma-simulation/logs")
CARMA_LOG_DIRECTORY = Path("/opt/carma/logs")
V2XHUB_DIRECTORY = Path("/opt/v2xhub")
V2XHUB_DOWNLOAD_DIRECTORY = V2XHUB_DIRECTORY / "download"
V2XHUB_SSL_DIRECTORY = V2XHUB_DIRECTORY / "ssl"
V2XHUB_LOG_DIRECTORY = V2XHUB_DIRECTORY / "logs"
LEGACY_V2XHUB_LOG_DIRECTORY = Path("/tmp/cdasim-scenario-runner")
ALLOWED_HOST_DIRECTORY_ROOTS = (
    SIMULATION_TMP_DIRECTORY,
    SIMULATION_LOG_DIRECTORY,
    CARMA_LOG_DIRECTORY,
    MAP_TARGET_DIRECTORY,
    ROUTE_TARGET_DIRECTORY,
    V2XHUB_DIRECTORY,
    LEGACY_V2XHUB_LOG_DIRECTORY,
)
# Shell convention: an exit caused by signal N uses status 128 + N. SIGINT,
# generated by Ctrl+C, is signal 2, so Scenario Runner exits with status 130.
SIGINT_EXIT_CODE = 130


class ScenarioRunner:
    """Run or generate test cases defined in a scenario configuration."""

    def __init__(
        self,
        config_path: str = "config/scenarios/town10.yaml",
        generate_only: bool = False,
        test_case_label: str = None,
    ):
        if test_case_label is not None and not generate_only:
            raise ValueError("test_case_label requires generate_only=True")
        self.config_path = Path(config_path)
        self.generate_only = generate_only
        self.test_case_label = test_case_label
        self.test_cases = []
        self.tmp_dir = Path("tmp").resolve()
        self.collector = DataCollector()
        self.analyzer = DataAnalyzer()

    def load_parameters(self):
        if not self.config_path.exists():
            raise FileNotFoundError(f"{self.config_path} not found")
        with open(self.config_path, 'r') as f:
            data = yaml.safe_load(f)
        self.test_cases = data.get("test_cases", [])
        if not self.test_cases:
            raise ValueError(f"No 'test_cases' found in {self.config_path}")
        print(f"Loaded {len(self.test_cases)} scenario(s)")

    def _selected_test_cases(self):
        """Return indexed test cases, optionally filtered by label."""

        indexed_cases = list(enumerate(self.test_cases, start=1))
        if self.test_case_label is None:
            return indexed_cases

        matches = [
            (index, case)
            for index, case in indexed_cases
            if case.get("label", f"scenario_{index}") == self.test_case_label
        ]
        if not matches:
            available = ", ".join(
                case.get("label", f"scenario_{index}")
                for index, case in indexed_cases
            )
            raise ValueError(
                f"Test case {self.test_case_label!r} was not found. "
                f"Available test cases: {available}"
            )
        if len(matches) > 1:
            raise ValueError(
                f"Test case label {self.test_case_label!r} is not unique"
            )
        return matches

    @staticmethod
    def _configured_file(directory: Path, name: str, suffix: str) -> Path:
        """Resolve a configured map or route inside an allowed directory.

        Args:
            directory: Directory that must contain the configured file.
            name: Configured file name, with or without the expected suffix.
            suffix: Expected extension including its leading period, such as
                ``.osm`` or ``.csv``.

        Returns:
            The absolute, resolved file path. The file is not required to exist;
            callers that require it must check the returned path.

        Raises:
            ValueError: If the resolved path escapes ``directory``.

        Example:
            ``ScenarioRunner._configured_file(MAP_DIRECTORY, "Town10", ".osm")``
            resolves to ``<MAP_DIRECTORY>/Town10.osm``.
        """

        filename = name if name.endswith(suffix) else f"{name}{suffix}"
        source = (directory / filename).resolve()
        try:
            source.relative_to(directory.resolve())
        except ValueError as exc:
            raise ValueError(f"Invalid configured file name: {name}") from exc
        return source

    def _scenario_resources(self, case: dict, label: str) -> dict:
        """Validate and describe the resources required by one test case.

        Args:
            case: Test-case mapping from the scenario configuration. It must
                contain a ``MAP`` value and may contain vehicle
                ``SELECTED_ROUTE`` values under
                ``env_settings.vehicles[*].settings``.
            label: Test-case label used to identify configuration errors.

        Returns:
            A dictionary of resources required for a test case. Each resources should 
            include :
                source: source file to be used
                target: path to target location of resource
                name: a unique name for the resource
            additionally each resource will either be associated with a vehicle, infrastructure instance, or test case.
            

        Raises:
            ValueError: If ``MAP`` is missing or a configured name resolves
                outside its allowed configuration directory.
            FileNotFoundError: If the configured resource does not
                exist under ``config/maps`` or ``config/routes`` or ``config/infrastrucure``.

        Example:
            ``resources = runner._scenario_resources(case, case["label"])``
            prepares the data passed to ``ScenarioGenerator``.
        """

        map_name = case.get("MAP")
        if not map_name:
            raise ValueError(
                f"MAP is not specified for test case {label}"
            )

        map_source = self._configured_file(MAP_DIRECTORY, str(map_name), ".osm")
        if not map_source.is_file():
            raise FileNotFoundError(
                f"{map_name} map specified for test case "
                f"{label} cannot be found at {map_source}"
            )
        # Setup CDA Sim Resources
        cdasim_configs = []
        cdasim_resources  = case.get("env_settings",{}).get("cdasim",{}).get("settings",{}).get("CDASIM_RESOURCES",{})
        for resource_name, resource_value in cdasim_resources.items():
            source = self._configured_file( 
                CDASIM_CONFIG_DIRECTORY / resource_name, resource_value, ""
            )
            if not source.is_file():
                            raise FileNotFoundError(
                                f"{resource_name} configuration specified for "
                                f" test case {label} cannot be found in {source}!" 
                            )
            target = self.tmp_dir / resource_name
            cdasim_configs.append(
                {
                    "source": str(source),
                    "target": str(target),
                    "name": str(resource_name),
                    "test_case": str(label)
                }
            ) 
        routes = []
        route_targets = set()
        vehicles = case.get("env_settings", {}).get("vehicles", [])
        for vehicle in vehicles:
            settings = vehicle.get("settings", {})
            route_name = settings.get("SELECTED_ROUTE")
            if not route_name:
                continue

            vehicle_name = settings.get("VEHICLE_ID", vehicle.get("PROJECT_NAME"))
            route_source = self._configured_file(
                ROUTE_DIRECTORY, str(route_name), ".csv"
            )
            if not route_source.is_file():
                raise FileNotFoundError(
                    f"{route_name} route specified for "
                    f"vehicle {vehicle_name} cannot be found at {route_source}"
                )

            route_target = ROUTE_TARGET_DIRECTORY / route_source.name
            if route_target in route_targets:
                continue
            route_targets.add(route_target)
            routes.append(
                {
                    "source": str(route_source),
                    "target": str(route_target),
                    "name": str(route_name),
                    "vehicle": str(vehicle_name),
                }
            )
        # Return empty dictionary if no infrastructure instance are found
        infrastructure_instances = case.get("env_settings", {}).get("streets")
        infrastructure_configs = []
        # If no infrastructure instances, replace with empty list to avoid for loop with non iterable.
        for infra in infrastructure_instances or []:
            settings = infra.get("settings")
            # infra_config = settings.get("INFRASTRUCTURE_CONFIG")
            infra_name = infra.get("PROJECT_NAME")

            infrastructure_resources = settings.get("INFRASTRUCTURE_RESOURCES", {})
            for resource_name, resource_value in infrastructure_resources.items():
                source = self._configured_file( 
                    INFRASTRUCTURE_CONFIG_DIRECTORY / resource_name, resource_value, ""
                )
                if not source.is_file():
                                raise FileNotFoundError(
                                    f"{resource_name} configuration specified for "
                                    f" streets instance {infra_name} cannot be found in {source}!" 
                                )
                target_folder_name = resource_name + "_" + infra_name
                target = self.tmp_dir / target_folder_name
                infrastructure_configs.append(
                    {
                        "source": str(source),
                        "target": str(target),
                        "name": str(resource_name),
                        "infrastructure": str(infra_name)
                    }
                )

        return {
            "map_file": {
                "source": str(map_source),
                "target": str(MAP_TARGET_DIRECTORY / "vector_map.osm"),
                "name": str(map_name),
                "test_case": label,
            },
            "routes": routes,
            "infrastructure_configs": infrastructure_configs,
            "cdasim_configs": cdasim_configs
        }

    @staticmethod
    def _normalize_vehicle_runtime_settings(case: dict) -> None:
        """Normalize float-valued ROS 2 settings for every configured vehicle.

        Args:
            case: Mutable test-case mapping. For each vehicle that defines
                ``START_DELAY_IN_SECONDS``, this function replaces an integer,
                float, or numeric string with a finite ``float`` value.

        Returns:
            None. The supplied ``case`` is updated in place.

        Raises:
            ValueError: If ``START_DELAY_IN_SECONDS`` is a boolean, cannot be
                converted to a number, or converts to a non-finite value.

        Example:
            Calling ``ScenarioRunner._normalize_vehicle_runtime_settings(case)``
            converts ``START_DELAY_IN_SECONDS: 30`` to ``30.0``.
        """

        vehicles = case.get("env_settings", {}).get("vehicles", [])
        for vehicle in vehicles:
            settings = vehicle.get("settings", {})
            if "START_DELAY_IN_SECONDS" not in settings:
                continue

            value = settings["START_DELAY_IN_SECONDS"]
            vehicle_name = settings.get(
                "VEHICLE_ID", vehicle.get("PROJECT_NAME", "unknown")
            )
            if isinstance(value, bool):
                raise ValueError(
                    "START_DELAY_IN_SECONDS for vehicle "
                    f"{vehicle_name} must be numeric, not {value!r}"
                )
            try:
                normalized_value = float(value)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    "START_DELAY_IN_SECONDS for vehicle "
                    f"{vehicle_name} must be numeric, not {value!r}"
                ) from exc
            if not math.isfinite(normalized_value):
                raise ValueError(
                    "START_DELAY_IN_SECONDS for vehicle "
                    f"{vehicle_name} must be finite, not {value!r}"
                )
            settings["START_DELAY_IN_SECONDS"] = normalized_value

    @staticmethod
    def _validated_host_directory(path: Path) -> Path:
        """Resolve a host directory and ensure it is under an allowed root."""

        candidate = Path(path).expanduser()
        if not candidate.is_absolute():
            raise ValueError(f"Host directory must be absolute: {candidate}")

        resolved = candidate.resolve(strict=False)
        allowed_roots = [
            root.resolve(strict=False) for root in ALLOWED_HOST_DIRECTORY_ROOTS
        ]
        if not any(
            resolved == root or root in resolved.parents
            for root in allowed_roots
        ):
            raise ValueError(f"Host directory is outside allowed roots: {resolved}")
        return resolved

    def _host_directories(self, case: dict) -> list[Path]:
        """Return host directories required by one normalized test case."""

        directories = {
            SIMULATION_TMP_DIRECTORY,
            SIMULATION_LOG_DIRECTORY,
            CARMA_LOG_DIRECTORY,
            MAP_TARGET_DIRECTORY,
            ROUTE_TARGET_DIRECTORY,
            V2XHUB_DOWNLOAD_DIRECTORY,
            V2XHUB_SSL_DIRECTORY,
            V2XHUB_LOG_DIRECTORY,
        }

        collect = case.get("data_output", {}).get("collect", {})
        directories.update(Path(path) for path in collect.values() if path)

        mosaic_log_root = collect.get("mosaic_logs")
        if mosaic_log_root:
            directories.add(Path(mosaic_log_root) / "carla-sensor-lib")

        rosbag_root = collect.get("rosbags")
        if rosbag_root:
            for vehicle in case.get("env_settings", {}).get("vehicles", []):
                vehicle_id = str(vehicle["settings"]["VEHICLE_ID"])
                vehicle_part = Path(vehicle_id)
                if (
                    vehicle_part.is_absolute()
                    or len(vehicle_part.parts) != 1
                    or vehicle_id in {".", ".."}
                ):
                    raise ValueError(
                        f"VEHICLE_ID must be one path component: {vehicle_id!r}"
                    )
                directories.add(Path(rosbag_root) / vehicle_id)

        return sorted(
            {self._validated_host_directory(path) for path in directories},
            key=str,
        )

    @staticmethod
    def _prepare_host_directory(directory: Path) -> None:
        """Create one host directory and make it writable by all containers."""

        try:
            directory.mkdir(parents=True, exist_ok=True)
        except PermissionError:
            print(f"Requesting elevated permission to create {directory}...")
            subprocess.run(
                ["sudo", "mkdir", "-p", "--", str(directory)],
                check=True,
            )

        current_mode = stat.S_IMODE(directory.stat().st_mode)
        if current_mode & 0o777 == 0o777:
            return

        try:
            directory.chmod(current_mode | 0o777)
        except PermissionError:
            print(
                "Requesting elevated permission to make "
                f"{directory} writable..."
            )
            subprocess.run(
                ["sudo", "chmod", "a+rwx", "--", str(directory)],
                check=True,
            )

    def _prepare_host_directories(self, case: dict) -> None:
        """Prepare every host directory required before Compose starts."""

        for directory in self._host_directories(case):
            self._prepare_host_directory(directory)
            print(f"Prepared {directory}")

    def _run_one(self, idx: int, case: dict) -> tuple[Path | None, dict] | None:
        """Generate, execute, stop, and collect data for one test case.

        Args:
            idx: One-based scenario number used for display and data collection.
            case: Test-case mapping loaded from the scenario configuration.

        Returns:
            A ``(case_dir, case)`` tuple identifying the collected data, or
            ``None`` if ``--generate-only`` was passed and nothing was run
            or collected.

        Raises:
            FileNotFoundError: If a required map, route, Compose file, or config
                image resource cannot be found.
            ValueError: If the test-case configuration is invalid.
            subprocess.CalledProcessError: If the generated start script fails.
            KeyboardInterrupt: If the user interrupts execution with Ctrl+C;
                the stop script still runs from the ``finally`` block.

        Example:
            ``runner._run_one(1, runner.test_cases[0])`` executes the first
            loaded case. Normal callers should use ``runner.run()`` instead.
        """
        label = case.get("label", f"scenario_{idx}")
        scenario_resources = self._scenario_resources(case, label)
        case = apply_scenario_topology(case)
        self._normalize_vehicle_runtime_settings(case)
        print(f"\n=== Scenario {idx}: {label} ===")

        # 1. Clean tmp/ (fresh start)
        if self.tmp_dir.exists():
            shutil.rmtree(self.tmp_dir)
        self.tmp_dir.mkdir()

        # 2. Write the resolved test-case configuration to tmp/.
        scenario_config_file_name = label+"_scenario.yaml"
        param_path = self.tmp_dir / scenario_config_file_name
        with open(param_path, "w") as f:
            yaml.dump(
                {
                    "env_settings": case["env_settings"],
                    "scenario_resources": scenario_resources,
                },
                f,
                default_flow_style=False,
            )
        print(f"Generated {param_path}")

        # 3. Generate scripts
        gen = ScenarioGenerator(
            config_path=str(param_path),
            compose_root=self.config_path.parent,
        )
        scripts = gen.generate()
        start_sh = scripts["start_script"]
        stop_sh = scripts["stop_script"]

        if self.generate_only:
            print(
                f"Scenario {idx} generated. "
                f"Inspect files in {self.tmp_dir}.\n"
            )
            return None

        print("Clearing source log directories...")
        self.collector.clear_sources(case)

        print("Preparing host directories...")
        self._prepare_host_directories(case)

        try:
            # 4. Start
            print(f"Launching: {start_sh}")
            subprocess.run(["bash", start_sh], check=True)

            # 5. Wait
            runtime = case.get("runtime_seconds", 60)
            print(f"Running {label} for  {runtime} seconds...")
            time.sleep(runtime)
        except subprocess.CalledProcessError as e:
            print(f"Start script {start_sh} failed with error : {e}")
        except KeyboardInterrupt:
            print("Interrupt received; stopping the scenario...")
            raise
        finally:
            # 6. Stop
            print(f"Stopping: {stop_sh}")
            # Cleanup is best-effort so it does not hide the original startup
            # failure or keyboard interrupt.
            stop_result = subprocess.run(["bash", stop_sh], check=False)
            if stop_result.returncode != 0:
                print(
                    f"Warning: stop script exited with "
                    f"{stop_result.returncode}"
                )

        print("Collecting data outputs...")
        case_dir = self.collector.collect(idx, case)

        # 7. ALWAYS clean tmp/
        shutil.rmtree(self.tmp_dir)
        print(f"Cleaned {self.tmp_dir}")

        print(f"Scenario {idx} complete.\n")
        return case_dir, case

    def run(self):
        if not self.test_cases:
            self.load_parameters()

        selected_cases = self._selected_test_cases()
        if self.test_case_label is not None:
            print(f"Generating selected test case: {self.test_case_label}")

        collected = []
        for i, case in selected_cases:
            try:
                result = self._run_one(i, case)
                if result:
                    collected.append(result)
            except KeyboardInterrupt:
                print(f"Scenario {i} interrupted by user")
                if not self.generate_only and self.tmp_dir.exists():
                    shutil.rmtree(self.tmp_dir)
                raise SystemExit(SIGINT_EXIT_CODE)
            except Exception as e:
                print(f"Scenario {i} failed: {e}")
                if not self.generate_only and self.tmp_dir.exists():
                    shutil.rmtree(self.tmp_dir)

        if not self.generate_only:
            self.collector.clear_sources(case)

        analysis_failures = {}
        for case_dir, case in collected:
            print("Running data analysis...")
            label = case.get("label", str(case_dir))
            failures = self.analyzer.analyze(case_dir, case)
            if failures:
                analysis_failures[label] = failures

        if analysis_failures:
            print("\n=== Data analysis failures ===")
            for label, failures in analysis_failures.items():
                print(f"{label}:")
                for failure in failures:
                    print(f"  - {failure}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Run CDASim scenarios")
    parser.add_argument(
        "--config",
        default="config/scenarios/town10.yaml",
        metavar="PATH",
        help=(
            "Scenario configuration file "
            "(default: config/scenarios/town10.yaml)"
        ),
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Generate environment and start/stop files without executing them",
    )
    parser.add_argument(
        "--test-case",
        metavar="LABEL",
        help="Generate only the test case with this label",
    )
    args = parser.parse_args(argv)
    if args.test_case and not args.generate_only:
        parser.error("--test-case requires --generate-only")
    return args


if __name__ == "__main__":
    args = parse_args()
    ScenarioRunner(
        config_path=args.config,
        generate_only=args.generate_only,
        test_case_label=args.test_case,
    ).run()
