services:
  econolite-virtual-controller:
    volumes:
      - type: bind
        source: "${EVC_SUMO_RESOURCE_PATH:?EVC_SUMO_RESOURCE_PATH is required}/tl_468.cfg"
        target: /home/carma/src/resources/tl_468.cfg
        read_only: true
