services:
  econolite-virtual-controller:
    volumes:
      - type: bind
        source: "${EVC_SUMO_RESOURCE_PATH:?EVC_SUMO_RESOURCE_PATH is required}/${EVC_SUMO_CFG_FILE:-evc_sumo_cfg_468_719_189.json}"
        target: /home/carma/src/resources/evc_sumo_cfg.json
        read_only: true
