services:
  cdasim:
    volumes:
      - type: bind
        source: "${TOWN10_SUMO_RESOURCE_PATH:?TOWN10_SUMO_RESOURCE_PATH is required}/${CDASIM_RESOURCES_TOWN10_SUMO:?CDASIM_RESOURCES_TOWN10_SUMO is required}"
        target: /opt/carma-simulation/scenarios/Town10/sumo/Town10.sumocfg
        read_only: true
