services:
  # Add all V2X Hub instances to global infrastructure network
  v2xhub:
    networks:
      - infrastructure-net
      - sim_external
networks:
  infrastructure-net:
    name: "${INFRASTRUCTURE_NETWORK_NAME}"
    external: true
  sim_external:
    external: true
    name: "${SIM_NETWORK_NAME}"





