services:
  v2xhub:
    volumes:
      - type: bind
        source: "${SENSOR_RESOURCE_PATH:?SENSOR_RESOURCE_PATH is required}/sensors.json"
        target: /var/www/download/sensors.json
        read_only: true
